### ISSUE TITLE
Check if named route already exists?

### ISSUE THREAD

**Issue by fourpixels** [dizlexik/express-reverse#7]
Hi there,
First of all I would like to thank you big time for this one - I've posted a question to SO (http://stackoverflow.com/q/32121209/2065080) and nobody seems to find a solution. I found your by accident, but I'm very happy for now :)

I just wanted to mention that I think there should be a check in verbs augmentation, so that if there is already a route with the same name, at least a warning is written in the console. Because if you use two names on routes (happens in big projects), the first one gets overriden and it disappears :)

Thanks!

**Comment by dizlexik** [comment]
Good catch :)
And I'm glad it's working well for you!
